spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_eventclean
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enable: true

server:
  port: 8080